#!/bin/bash

sudo chown -R www-data:www-data /var/www/html
echo "group set to www-data"

sudo find /var/www/html/ -type d -exec chmod 0755 {} \;
echo "directory permissions set to 755"

sudo find /var/www/html/ -type f -exec chmod 0644 {} \;
echo "file permissions set to 644"


